modLoader="javafml"
loaderVersion="[32,)"
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="gourmandise"
version="${file.jarVersion}"
displayName="Gourmandise"
displayURL="https://discord.gg/BgE4EpP"
logoFile="logo.png"
authors="Team Aurora"
description="@everyone grape"

[[dependencies.gourmandise]]
modId="forge"
mandatory=true
versionRange="[35.1.10,)"
ordering="NONE"
side="BOTH"

[[dependencies.gourmandise]]
modId="minecraft"
mandatory=true
versionRange="[1.16.4]"
ordering="NONE"
side="BOTH"

[[dependencies.gourmandise]]
modId="abnormals_core"
mandatory=true
versionRange="[3.0.6,)"
ordering="AFTER"
side="BOTH"